// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyfdvluiebpcmrvcwjxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5ZmR2bHVpZWJwY21ydmN3anhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MzMzMTMsImV4cCI6MjA2MzAwOTMxM30.sSA232SJyNmBgNqBcK7LxFUiIszWR10iCUiqsS8mqNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);